<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Linear Algebra

---

## Learning Objectives

- Compute dot products, matrix multiplications, and vector norms by hand and using NumPy.

# Introduction

Linear algebra is the most important area of math for data analysis. Computers are great at it, and it can be used for a huge variety of purposes. In machine learning, it's used in both relatively simple methods such as linear regression and cutting-edge methods in deep learning.

If you are already familiar with linear algebra, then this quick review will help prime your memory. If you are not, then it will introduce you to the terminology you need for this course and lay a foundation for further study.

# NumPy

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact
plt.style.use('fivethirtyeight')

# This makes sure that graphs render in your notebook
%matplotlib inline

NumPy arrays look similar to Python lists, but they are optimized for doing matrix and vector math instead of for serving as general-purpose containers.

- Basic mathematical operations are applied using elementwise arithmetic.

In [2]:
# /scrub/
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [3]:
# /scrub/
np.array([1, 2, 3]) + np.array([4, 5, 6])

array([5, 7, 9])

- Levels of nesting are interpreted as dimensions.

In [4]:
# /scrub/
[[1, 2], [3, 4], [5, 6]]

[[1, 2], [3, 4], [5, 6]]

In [5]:
# /scrub/
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
# Get shape
# /scrub/
a.shape

(3, 2)

- `pandas` DataFrames are built on top of Numpy arrays

In [7]:
b = pd.DataFrame({'x': [1, 3, 5], 'y': [2, 4, 6]})
b

x  y
0  1  2
1  3  4
2  5  6

In [8]:
# Pull out the underlying numpy array
# /scrub/
b.values

array([[1, 2],
       [3, 4],
       [5, 6]])

# Scalars, Vectors, and Matrices

- A **scalar** is single number, e.g. $a=5.328$ or $b=7$.
- A **vector** is an ordered sequence of numbers, e.g. $\vec{u} = \left[ \begin{array}{c} 1&3&7 \end{array} \right]$

An $m\times n$ **matrix** is a rectangular array of numbers with $m$ rows and $n$ columns. The entry in the $i$th row and $j$th column of a matrix $\mathbf{A}$ is denoted $a_{ij}$.

$$\mathbf{A}= \left[ \begin{array}{c}
a_{11} & a_{12} & ... & a_{1n}  \\
a_{21} & a_{22} & ... & a_{2n}  \\
... & ... & ... & ... \\
a_{m1} & a_{m2} & ... & a_{mn}
\end{array} \right]$$

Unfortunately, mathematicians typically start counting with 1, while in Python we start with 0.

**Exercise.** What is $m_{32}$ in this example, using mathematician's notation?

In [9]:
M = np.array([[1, 3, 7], [2, 6, 3], [9, 8, 0], [4, 5, 6]])
M

array([[1, 3, 7],
       [2, 6, 3],
       [9, 8, 0],
       [4, 5, 6]])

/scrub/

8

### Basic Matrix Algebra

#### Addition and Subtraction
Vector **addition** is done elementwise:

$\vec{v} + \vec{w} =
\left[ \begin{array}{c}
1 \\
3 \\
7
\end{array} \right] + \left[ \begin{array}{c}
1 \\
0 \\
1
\end{array} \right] = 
\left[ \begin{array}{c}
1+1 \\
3+0 \\
7+1
\end{array} \right] = 
\left[ \begin{array}{c}
2 \\
3 \\
8
\end{array} \right]
$

So is vector **subtraction**:

$\vec{v} - \vec{w} =
\left[ \begin{array}{c}
1 \\
3 \\
7
\end{array} \right] - \left[ \begin{array}{c}
1 \\
0 \\
1
\end{array} \right] = 
\left[ \begin{array}{c}
1-1 \\
3-0 \\
7-1
\end{array} \right] = 
\left[ \begin{array}{c}
0 \\
3 \\
6
\end{array} \right]
$

In [10]:
v = np.array([1, 3, 7])
w = np.array([1, 0, 1])

In [11]:
# Add and subtract
# /scrub/
print(v+w)
print(v-w)

[2 3 8]
[0 3 6]


Likewise for matrices.

Addition:

$\left[ \begin{array}{c}
1 & 2 & 6  \\
4 & 8 & 3  \\
9 & 2 & 1 \\
\end{array} \right]
+
\left[ \begin{array}{c}
9 & 7 & 3  \\
6 & 8 & 2  \\
4 & 2 & 4 \\
\end{array} \right]
=
\left[ \begin{array}{c}
1+9 & 2+7 & 6+3  \\
4+6 & 8+8 & 3+2  \\
9+4 & 2+2 & 1+4 \\
\end{array} \right]
=
\left[ \begin{array}{c}
10 & 9 & 9  \\
10 & 16 & 5  \\
13 & 4 & 5 \\
\end{array} \right]
$

Subtraction:

$\left[ \begin{array}{c}
1 & 2 & 6  \\
4 & 8 & 3  \\
9 & 2 & 1 \\
\end{array} \right]
-
\left[ \begin{array}{c}
9 & 7 & 3  \\
6 & 8 & 2  \\
4 & 2 & 4 \\
\end{array} \right]
=
\left[ \begin{array}{c}
1-9 & 2-7 & 6-3  \\
4-6 & 8-8 & 3-2  \\
9-4 & 2-2 & 1-4 \\
\end{array} \right]
=
\left[ \begin{array}{c}
-8 & -5 & 3  \\
-2 & 0 & 1  \\
5 & 0 & -3 \\
\end{array} \right]
$

In [12]:
a = np.array([[1, 2, 6], [4, 8, 3], [9, 2, 1]])
b = np.array([[9, 7, 3], [6, 8, 2], [4, 2, 4]])

In [13]:
# Add and subtract
# /scrub/
print(a+b)
print(a-b)

[[10  9  9]
 [10 16  5]
 [13  4  5]]
[[-8 -5  3]
 [-2  0  1]
 [ 5  0 -3]]


#### Multiplication

Multiplying with vectors and matrices can take a few different forms.

##### Elementwise multiplication

$\vec{v} + \vec{w} =
\left[ \begin{array}{c}
1 \\
3 \\
7
\end{array} \right] * \left[ \begin{array}{c}
1 \\
0 \\
1
\end{array} \right] = 
\left[ \begin{array}{c}
1*1 \\
3*0 \\
7*1
\end{array} \right] = 
\left[ \begin{array}{c}
1 \\
0 \\
7
\end{array} \right]
$


In [14]:
v = np.array([1, 3, 7])
w = np.array([1, 0, 1])

In [15]:
# Multiply elementwise
# /scrub/
print(v*w)

[1 0 7]


##### Scalar Multiplication: A Vector of Matrix times a *Number*
We scale a vector or matrix with **scalar multiplication**, multiplying a vector by a scalar (single quantity):

$ 2 \cdot \vec{v} = 2\left[ \begin{array}{c}
1 \\
3 \\
7
\end{array} \right] = 
 \left[ \begin{array}{c}
2 \cdot 1 \\
2 \cdot 3 \\
2 \cdot 7
\end{array} \right] = 
 \left[ \begin{array}{c}
2 \\
6 \\
14
\end{array} \right]$ 

$3
\cdot \left[ \begin{array}{c}
1 & 2 & 6  \\
4 & 8 & 3  \\
9 & 2 & 1 \\
\end{array} \right]
=
\left[ \begin{array}{c}
3\cdot1 & 3\cdot2 & 3\cdot6  \\
3\cdot4 & 3\cdot8 & 3\cdot3  \\
3\cdot9 & 3\cdot2 & 3\cdot1 \\
\end{array} \right]
=
\left[ \begin{array}{c}
3 & 6 & 18  \\
12 & 24 & 9  \\
27 & 6 & 3 \\
\end{array} \right]
$

In [16]:
v = np.array([1, 3, 7])

In [17]:
# Multiply by a scalar
# /scrub/
2 * v

array([ 2,  6, 14])

In [18]:
v = np.array([[1, 2, 6], [4, 8, 3], [9, 2, 1]])

In [19]:
# Multiply by a scalar
# /scrub/
3 * v

array([[ 3,  6, 18],
       [12, 24,  9],
       [27,  6,  3]])

##### Dot Product: Multiplying *Two Vectors* and Reducing the Result to a Single Number
Suppose three girl scout troops have 1, 3, and 7 members, respectively. Each member of the first troop sells 5 boxes of girl scout cookies; each member of the second troop sells 4; and each member of the third troop sells 2. How many boxes did they sell in all?

$1 \cdot 5 + 3 \cdot 4 + 7 \cdot 2 = 5 + 12 + 14 = 31$

This calculation is an examples of a **dot product**, which you calculate by multiplying corresponding elements of two vectors and adding the results:

$\vec{v} = \left[ \begin{array}{c}
1 \\
3 \\
7
\end{array} \right], \vec{w} = \left[ \begin{array}{c}
5 \\
4 \\
2
\end{array} \right]$

$ \vec{v} \cdot \vec{w} = 1 \cdot 5 + 3 \cdot 4 + 7 \cdot 2 = 31 $

If you think of vectors as arrows in space, then the dot product of two vectors reflects both *how big they are* and *the extent to which they point in the same direction.*

/scrub/

![](../assets/images/dot_product_sizes.png)

In [20]:
v = np.array([1, 3, 7])
w = np.array([5, 4, 2])

In [21]:
# Calculate the dot product of v and w
# /scrub/
print(v@w)  # new syntax, recommended
print(v.dot(w))  # old syntax, still common

31
31


##### Matrix Multiplication
Matrix multiplication, $\mathbf{A}_{mn}$ x $\mathbf{B}_{ij}$, is valid when the left matrix has the same number of columns as the right matrix has rows ($n = i$). Each entry is the dot product of corresponding row and column vectors.

![](../assets/images/matrix-multiply-a.gif)
(Image: mathisfun.com!)

/scrub/

![](../assets/images/matrix_multiplication.png)

**Convention:** Use capital letters for matrices, lowercase for vectors.

In [22]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

In [23]:
# Calculate the matrix product of A and B
# /scrub/
print(A @ B)
print(A.dot(B))

[[ 58  64]
 [139 154]]
[[ 58  64]
 [139 154]]


**Exercise.** Compute this matrix product by hand, and then with Python. Make sure that your answers agree!

$
\left[ \begin{array}{c}
1 & 2 \\
4 & 8 \\
\end{array} \right]
\times \left[ \begin{array}{c}
2 & 9 \\
3 & 6 \\
\end{array} \right]
$

/scrub/

$
\left[ \begin{array}{c}
1\cdot2 + 2\cdot3 & 1\cdot9 + 2\cdot6 \\
4\cdot2 + 8\cdot3 & 4\cdot9 + 8\cdot6 \\
\end{array} \right]
= \left[ \begin{array}{c}
8 & 21 \\
32 & 84 \\
\end{array} \right]
$

In [24]:
# /scrub/
A = np.array([[1, 2], [4, 8]])
B = np.array([[2, 9], [3, 6]])

print(A @ B)

[[ 8 21]
 [32 84]]


<a id="vector-norm"></a>
##### Vector Norm

The dot product of a vector with **itself** just reflects how big that vector is. The *square root* of that number is the *length of the arrow*. This value is often called the vector's **norm** or **magnitude**.

$
\vec{v} = \left[ \begin{array}{c}
3 \\
4
\end{array}\right]
$

$
||\vec{v}||=\sqrt{\vec{v}\cdot\vec{v}} \\
= \sqrt{3\cdot3 + 4\cdot4} \\
= \sqrt{9 + 16} \\
= \sqrt{25} \\
= 5
$

In [25]:
x = np.array([3,4])

In [26]:
# Calculate the norm of the vector x with np.linalg.norm.
# /scrub/
np.linalg.norm(x)

5.0

<a id="linear-algebra-applications-to-machine-learning"></a>
# Example Application to Machine Learning

Linear regression finds the set of coefficients that maximize predictive accuracy on some training data, meaning that it minimizes the **norm** of the **difference** between the **vector** of its predictions and the **vector** of true values.

$$\| \vec{actual} - \vec{predicted} \| =\sqrt{(actual_1 - predicted_1)^2 + (actual_2 - predicted_2)^2}$$

The algorithm it uses to find those coefficients simply **inverts** and **multiplies matrices**.